---
title: "ACP_University"
author: "Moussa"
date: "2024-08-18"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#####  Import of dataset ###############
```{r}
library(readxl)
universite <- read_excel("~/GitHub/SORADATA/ACP-R/Dataset/universite.xlsx")

```
```{r}
str(universite)
```

#### Les statistiques descriptives ################
```{r}
summary(universite)
```

```{r}
aggregate(Master~Doctorat, data = universite, FUN = mean)

```


```{r}
library(ggplot2)

# Préparer les données pour ggplot
universite_long <- tidyr::pivot_longer(universite, cols = c(`Doctorat-F`, `Doctorat-H`, `Master-F`, `Master-H`), 
                                       names_to = c("Niveau", "Sexe"), names_sep = "-", values_to = "Valeurs")

# Créer l'histogramme avec ggplot pour Doctorat et Master
ggplot(universite_long, aes(x = Valeurs, fill = Sexe)) + 
  geom_histogram(alpha = 0.5, position = "identity") +
  facet_wrap(~Niveau) +
  labs(title = "Comparaison Doctorat et Master par Sexe", x = "Valeurs", y = "Fréquence") +
  scale_fill_manual(values = c("blue", "red", "green", "orange"))

```

```{r}
library(ggplot2)

# Préparer les données au format long
universite_long <- tidyr::pivot_longer(universite, cols = c(`Doctorat-F`, `Doctorat-H`, `Master-F`, `Master-H`), 
                                       names_to = c("Niveau", "Sexe"), names_sep = "-", values_to = "Valeurs")

# Créer le boxplot avec ggplot
ggplot(universite_long, aes(x = interaction(Niveau, Sexe), y = Valeurs, fill = Sexe)) +
  geom_boxplot() +
  labs(title = "Boxplot Doctorat et Master par Sexe", x = "Niveau et Sexe", y = "Valeurs") +
  scale_fill_manual(values = c("lightblue", "lightpink")) +
  theme_minimal()

```
```{r}
# Calculer le total pour chaque filière
total_doctorat <- sum(universite$`Doctorat-F`) + sum(universite$`Doctorat-H`)
total_master <- sum(universite$`Master-F`) + sum(universite$`Master-H`)

# Calculer le total général
total_global <- total_doctorat + total_master

# Calculer les proportions
proportion_doctorat <- total_doctorat / total_global
proportion_master <- total_master / total_global

# Créer un vecteur des proportions
proportions <- c(proportion_doctorat, proportion_master)

# Créer un vecteur des noms des filières
filieres <- c("Doctorat", "Master")
library(ggplot2)

# Préparer les données dans un data frame
proportions_df <- data.frame(
  Filiere = filieres,
  Proportion = proportions
)

# Créer le barplot avec ggplot2
ggplot(proportions_df, aes(x = Filiere, y = Proportion, fill = Filiere)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +
  labs(title = "Proportions des Étudiants par niveau d'étude", x = "Niveau d'étude", y = "Proportion") +
  scale_fill_manual(values = c("lightblue", "lightgreen")) +
  theme_minimal() +
  geom_text(aes(label = scales::percent(Proportion)), vjust = -0.5)

```

#### ACP via FactomineR ##############

```{r}
library(FactoMineR)
library("factoextra")
```
```{r}
# Sélectionner uniquement les colonnes numériques
numerical_vars <- sapply(universite, is.numeric)

# Créer un sous-data frame avec uniquement les colonnes numériques
universite_numeric <- universite[, numerical_vars]

```


```{r}
resultat_ACP<-PCA(universite_numeric, graph = FALSE)
print(resultat_ACP)
```
### Le choix de l'axe ou de dimension ####

```{r}
valeurspropes<-resultat_ACP$eig
valeurspropes
```
```{r}
barplot(valeurspropes[,2],names.arg = 1:nrow(valeurspropes),
        main = "Pourcentage dela variance expliquée par chaque composante",
        xlab = "Composantes principales",
        ylab = "Pourcentage de variance expliquée",
        col = "steelblue")
lines(x=1:nrow(valeurspropes),valeurspropes[,2],
      type = "b",pch=19,col="red")




```

### Le cercle de corrélation ou il exite un effet de taille   ###
```{r}
fviz_pca_var(resultat_ACP,
             col.var = "cos2", # Coloration par le cosinus carré
             gradient.cols = c("#888AFB","#E78800","#FC4E07"), # Définir les couleurs du gradient
             repel = TRUE, # Éviter le chevauchement des étiquettes
             title = "Cercle de corrélation des variables") # Titre du graphique
```
```{r}
fviz_pca_ind(resultat_ACP, 
             col.ind = "cos2",  # Coloration en fonction du cos2
             gradient.cols = c("blue", "white", "red"),  # Palette de couleurs
             repel = TRUE) +  # Éviter le chevauchement des étiquettes
  scale_color_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0.50) +
  theme_minimal() +
  labs(title = "Visualisation des individus selon Cos2",
       color = "Cos2")
```
str(Universite)
